#!/usr/bin/env bash

DEFAULT_WORKSPACE="${HOME}/swap-devbox-workspace"
WORKSPACE="${DEFAULT_WORKSPACE}"

DEFAULT_INNER_WORKSPACE="/tmp"
PROJECT_INNER_WORKSPACE="/home/${USERNAME}/app"
INNER_WORKSPACE="$DEFAULT_INNER_WORKSPACE"

BASE_IMAGE_NAME="sirap/swap-devbox"
BASE_IMAGE_TAG="latest"
IMAGE_NAME="devbox"
IMAGE_TAG="latest"
CONTAINER="devbox"

if [[ ! -z "${USERNAME}" ]]; then
  username="${USERNAME}"
else
  username="${USER}"
fi


mkdir -p "${WORKSPACE}"

if [[ $1 == "build" ]]; then
  docker pull ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
  docker build \
    -t ${IMAGE_NAME}:${IMAGE_TAG} \
    --build-arg username=${username} \
    --build-arg password=${username} \
    --build-arg uid=$(echo $UID) \
    . \
    -f - <<\EOF
FROM sirap/swap-devbox
ARG username="developer"
ARG password="developer"
ARG uid="1000"
LABEL Author="Rémi Becheras <r.becheras@sirap.fr>"

USER 0
RUN deluser developer \
  && adduser \
    --disabled-password \
    --home "/home/${username}" \
    --shell /bin/bash \
    --uid "${uid}" \
    --gecos "" \
    "${username}" \
  && echo "${username}:${password}" | chpasswd


USER ${username}
EXPOSE 3000 8448
VOLUME [ "/data" ]
WORKDIR "/home/${username}/app"
CMD [ "bash" ]

EOF

elif [[ "$1" == "start" ]]; then
  if [[ ! -z "$2" ]]; then
    workspace="$2"
    pwd=$(pwd)
    cd $workspace
    WORKSPACE=$(pwd)
    cd $pwd

    INNER_WORKSPACE=$PROJECT_INNER_WORKSPACE
  fi;

  docker run --rm -itd \
    --name "${CONTAINER}" \
    --volume "${WORKSPACE}":"${INNER_WORKSPACE}" \
    --volume "/home/${USERNAME}/.gitconfig:/home/${USERNAME}/.gitconfig" \
    --volume "/home/${USERNAME}/.gnupg:/home/${USERNAME}/.gnupg" \
    --volume "/home/${USERNAME}/.ssh:/home/${USERNAME}/.ssh" \
    --net host \
    -w "${WORKSPACE}" \
    "${IMAGE_NAME}:${IMAGE_TAG}" \
  && echo "SWAP devbox successfully started.
Container Name: ${CONTAINER}
From Image: ${IMAGE_NAME}:${IMAGE_TAG}
Inner Workspace: ${INNER_WORKSPACE}
Outer Workspace: ${WORKSPACE}
Exposed ports: net host (all)"

elif [[ "$1" == "stop" ]]; then
  docker stop "${CONTAINER}" && echo "devbox stopped"

elif [[ "$1" == "bash" ]]; then
  if [[ "$2" == "-r" ]]
  then
    docker exec -it -u "0" -w "/root"  "${CONTAINER}" bash
  else
    docker exec -it -u "${UID}" -w "${INNER_WORKSPACE}" "${CONTAINER}" bash
  fi

else
  echo "devbox-ctl needs a command
Available commands: build, start, stop, bash"

fi